<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
    <None Include="Content\Equipment\Reworks\GuillotineEquipment.cs" />
    <None Include="Content\Interactables\Interactables\CurseStatue.cs" />
    <None Include="Content\Interactables\Interactables\FakeShrine.cs" />
    <None Include="Content\Interactables\QuestInteractables\EnergyCrystalAltar.cs" />
    <None Include="Content\Interactables\QuestInteractables\FlameAltar.cs" />
    <None Include="Content\Interactables\QuestInteractables\LunarBrandMaker.cs" />
    <None Include="Content\Interactables\QuestInteractables\SpineAltar.cs" />
    <None Include="Content\Interactables\QuestInteractables\SpineCharger.cs" />
    <None Include="Content\Items\SwanSong\QuestItems\EnergyCrystal.cs" />
    <None Include="Content\Items\SwanSong\QuestItems\FlameOrb.cs" />
    <None Include="Content\Items\SwanSong\QuestItems\MalachiteSpine.cs" />
    <None Include="Content\TwistedScavengers\BoboScav.cs" />
    <None Include="Content\TwistedScavengers\CunningScav.cs" />
    <None Include="Content\TwistedScavengers\GreedyScav.cs" />
    <None Include="Content\TwistedScavengers\SadistScav.cs" />
    <None Include="Content\TwistedScavengers\SpeedScav.cs" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
       
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.0-r.0" />
    <PackageReference Include="MMHOOK.RoR2" Version="2025.11.19" NoWarn="NU1701" />
    <PackageReference Include="RoR2BepInExPack" Version="1.36.0" />
    <PackageReference Include="BepInEx.Analyzers" Version="1.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="BepInEx.Core" Version="5.4.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" />
    <PackageReference Include="R2API" Version="5.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Content\Equipment\Reworks\GuillotineEquipment.cs" />
    <Compile Remove="Content\Interactables\Interactables\CurseStatue.cs" />
    <Compile Remove="Content\Interactables\Interactables\FakeShrine.cs" />
    <Compile Remove="Content\Interactables\QuestInteractables\EnergyCrystalAltar.cs" />
    <Compile Remove="Content\Interactables\QuestInteractables\FlameAltar.cs" />
    <Compile Remove="Content\Interactables\QuestInteractables\LunarBrandMaker.cs" />
    <Compile Remove="Content\Interactables\QuestInteractables\SpineAltar.cs" />
    <Compile Remove="Content\Interactables\QuestInteractables\SpineCharger.cs" />
    <Compile Remove="Content\Items\SwanSong\QuestItems\EnergyCrystal.cs" />
    <Compile Remove="Content\Items\SwanSong\QuestItems\FlameOrb.cs" />
    <Compile Remove="Content\Items\SwanSong\QuestItems\MalachiteSpine.cs" />
    <Compile Remove="Content\TwistedScavengers\BoboScav.cs" />
    <Compile Remove="Content\TwistedScavengers\CunningScav.cs" />
    <Compile Remove="Content\TwistedScavengers\GreedyScav.cs" />
    <Compile Remove="Content\TwistedScavengers\SadistScav.cs" />
    <Compile Remove="Content\TwistedScavengers\SpeedScav.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Wwise">
      <HintPath>libs\Wwise.dll</HintPath>
    </Reference>
    <Reference Include="AncientScepter">
      <HintPath>libs\AncientScepter.dll</HintPath>
    </Reference>
    <Reference Include="Decalicious">
      <HintPath>libs\Decalicious.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BetterSoulCost\BetterSoulCost.csproj" />
    <ProjectReference Include="..\BorboStatUtils\RainrotSharedUtils.csproj" />
    <ProjectReference Include="..\MissileRework\MissileRework.csproj" />
    <ProjectReference Include="..\NegativeRegenFix\NegativeRegenFix.csproj" />
    <ProjectReference Include="..\JumpRework\JumpRework.csproj" />
    <ProjectReference Include="..\BarrierRework\BarrierRework.csproj" />
    <ProjectReference Include="..\BossDropRework\BossDropRework.csproj" />
    <ProjectReference Include="..\MoreStats\MoreStats.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\Items\Vanilla\SOTS\" />
    <Folder Include="Content\Orbs\" />
  </ItemGroup>

</Project>
