<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
    <None Include="Changes\Reworks\AegisRework.cs" />
    <None Include="Changes\Reworks\BrittleCrownRework.cs" />
    <None Include="Changes\Reworks\ExeCardRework.cs" />
    <None Include="Changes\Reworks\FocusedConvergenceRework.cs" />
    <None Include="Changes\Reworks\GestureRework.cs" />
    <None Include="Changes\Reworks\HappiestMaskRework.cs" />
    <None Include="Changes\Reworks\HarpoonRework.cs" />
    <None Include="Changes\Reworks\LaserScopeRework.cs" />
    <None Include="Changes\Reworks\LeechingSeedRework.cs" />
    <None Include="Changes\Reworks\MeatRework.cs" />
    <None Include="Changes\Reworks\PlanulaRework.cs" />
    <None Include="Changes\Reworks\PrayerBeadsRework.cs" />
    <None Include="Changes\Reworks\RazorwireRework.cs" />
    <None Include="Changes\Reworks\RegenScrapRework.cs" />
    <None Include="Changes\Reworks\ResDiscDework.cs" />
    <None Include="Changes\Reworks\SquidPolypRework.cs" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
       
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RiskOfRain2.GameLibs" Version="*-*" />
    <PackageReference Include="MMHOOK.RoR2" Version="*" NoWarn="NU1701" />
    <PackageReference Include="RoR2BepInExPack" Version="*" />
    <PackageReference Include="BepInEx.Analyzers" Version="1.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="BepInEx.Core" Version="5.4.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" />
    <PackageReference Include="R2API" Version="5.0.5" />
    <PackageReference Include="R2API.RecalculateStats" Version="1.6.5" />
    <PackageReference Include="R2API.ProcType" Version="1.0.2" />
    <PackageReference Include="R2API.DamageType" Version="1.1.7" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Changes\Reworks\AegisRework.cs" />
    <Compile Remove="Changes\Reworks\BrittleCrownRework.cs" />
    <Compile Remove="Changes\Reworks\ExeCardRework.cs" />
    <Compile Remove="Changes\Reworks\FocusedConvergenceRework.cs" />
    <Compile Remove="Changes\Reworks\GestureRework.cs" />
    <Compile Remove="Changes\Reworks\HappiestMaskRework.cs" />
    <Compile Remove="Changes\Reworks\HarpoonRework.cs" />
    <Compile Remove="Changes\Reworks\LaserScopeRework.cs" />
    <Compile Remove="Changes\Reworks\LeechingSeedRework.cs" />
    <Compile Remove="Changes\Reworks\MeatRework.cs" />
    <Compile Remove="Changes\Reworks\PlanulaRework.cs" />
    <Compile Remove="Changes\Reworks\PrayerBeadsRework.cs" />
    <Compile Remove="Changes\Reworks\RazorwireRework.cs" />
    <Compile Remove="Changes\Reworks\RegenScrapRework.cs" />
    <Compile Remove="Changes\Reworks\ResDiscDework.cs" />
    <Compile Remove="Changes\Reworks\SquidPolypRework.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Wwise">
      <HintPath>libs\Wwise.dll</HintPath>
    </Reference>
    <Reference Include="AncientScepter">
      <HintPath>libs\AncientScepter.dll</HintPath>
    </Reference>
    <Reference Include="Decalicious">
      <HintPath>libs\Decalicious.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BetterSoulCost\BetterSoulCost.csproj" />
    <ProjectReference Include="..\BorboStatUtils\RainrotSharedUtils.csproj" />
    <ProjectReference Include="..\MissileRework\MissileRework.csproj" />
    <ProjectReference Include="..\NegativeRegenFix\NegativeRegenFix.csproj" />
    <ProjectReference Include="..\JumpRework\JumpRework.csproj" />
    <ProjectReference Include="..\BossDropRework\BossDropRework.csproj" />
    <ProjectReference Include="..\MoreStats\MoreStats.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Content\Orbs\" />
    <Folder Include="Content\Skills\Misc\" />
  </ItemGroup>

</Project>
