<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>preview</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
       
    </RestoreAdditionalProjectSources>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Content\Equipment\Aspects\FrenziedAspect.cs" />
    <Compile Remove="Content\Equipment\Aspects\LeechingAspect.cs" />
    <Compile Remove="Content\Equipment\Aspects\SimulatedAspect.cs" />
    <Compile Remove="Content\Equipment\Aspects\VolatileAspect.cs" />
    <Compile Remove="Content\States\Misc\LeechingHealNovaPulse.cs" />
    <Compile Remove="Modules\ItemDisplayCheck.cs" />
    <Compile Remove="Modules\ItemDisplays.cs" />
    <Compile Remove="Modules\Skins.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Content\Equipment\Aspects\FrenziedAspect.cs" />
    <None Include="Content\Equipment\Aspects\LeechingAspect.cs" />
    <None Include="Content\Equipment\Aspects\SimulatedAspect.cs" />
    <None Include="Content\Equipment\Aspects\VolatileAspect.cs" />
    <None Include="Content\States\Misc\LeechingHealNovaPulse.cs" />
    <None Include="Modules\ItemDisplayCheck.cs" />
    <None Include="Modules\ItemDisplays.cs" />
    <None Include="Modules\Skins.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.0-r.0" />
    <PackageReference Include="MMHOOK.RoR2" Version="2025.11.19" NoWarn="NU1701" />
    <PackageReference Include="RoR2BepInExPack" Version="1.36.0" />
    <PackageReference Include="BepInEx.Analyzers" Version="1.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="BepInEx.Core" Version="5.4.*" />
    <PackageReference Include="UnityEngine.Modules" Version="2021.3.33" />
    <PackageReference Include="R2API" Version="5.0.5" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BorboStatUtils\RainrotSharedUtils.csproj" />
    <ProjectReference Include="..\MissileRework\MissileRework.csproj" />
    <ProjectReference Include="..\MoreStats\MoreStats.csproj" />
    <ProjectReference Include="..\SwanSongExtended\SwanSongExtended.csproj" />
  </ItemGroup>
</Project>
